spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: auth-service
                  uri: lb://auth-service
                  predicates:
                    - Path=/auth/**
                - id: project-service
                  uri: lb://project-service
                  predicates:
                    - Path=/project/**


server:
    port: 8080
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        
    instance:
        preferIpAddress: true